### ISSUE TITLE
Missing reference to the September 2020 MaX webinar

### ISSUE THREAD

**Issue by jme52** [siesta-project/web-portal#3]
I think the website should refer at some point to the MaX webinar "New developments in SIESTA for high-performance materials simulations" (http://max-centre.eu/webinar/new-developments-siesta-high-performance-materials-simulations), but I am not sure what section this content to (outreach/showcase?).  It provides a nice overview of SIESTA, and its duration is reasonable ("five short talks plus Q&A").

**Comment by albgar** [comment]
It should go in the News section of the website, and to the mailing list. We sent an announcement of the webinar to the list, and a followup with the link is appropriate. 

For the News: currently there is no way to see new items up-front. For that we need to re-design the front page. Maybe there is a simple jekyll example for it.  I had the idea of using Twitter to post these kinds of things, and have a mini-window with the feed in the front page, but I do not like Twitter very much and have only posted a few things since I opened the account (SiestaDFT). 

This also touches on the larger communications issue in Gitlab.

**Comment by jme52** [comment]
PR #6 added to the website a page with the webinar shortly after this issue was created.

I just created issue #14, which addresses (amongst others) the issue with news and the front page.

Closing this now.
